en:
  extension.translate.name: Translate
  extension.translate.openplatform: iFLYTEK Open Platform authorization
  extension.translate.openplatform.description1: 'Please register your own '
  extension.translate.openplatform.description2: iFLYTEK Open Platform (Chinese)
  extension.translate.openplatform.description3: ' account, the test account we provide does not guarantee that every'
  extension.translate.translate: translate [WORDS] to [LANGUAGE]
  extension.translate.hello: hello
  extension.translate.english: English
  extension.translate.chinese.simplified: Chinese (Simplified)
  extension.translate.chinese.traditional: Chinese (Traditional)
  extension.translate.japanese: Japanese
  extension.translate.languageOf: language of [WORDS]
  extension.translate.language: language

zh-Hans:
  extension.translate.name: 翻译
  extension.translate.openplatform: 讯飞开放平台认证信息
  extension.translate.openplatform.description1: 请注册您自己的
  extension.translate.openplatform.description2: 讯飞开放平台
  extension.translate.openplatform.description3: 账号，我们提供的测试账号不保证每次请求都成功。
  extension.translate.translate: 将 [WORDS] 译为 [LANGUAGE]
  extension.translate.hello: 你好
  extension.translate.english: 英文
  extension.translate.chinese.simplified: 简体中文
  extension.translate.chinese.traditional: 繁体中文
  extension.translate.japanese: 日文
  extension.translate.languageOf: 识别 [WORDS] 的语言
  extension.translate.language: 访客语言
